apiVersion: v1
kind: Secret
metadata:
  name: mysql-creds
type: Opaque
data:
  rootHost: JQ==
  rootPassword: c2FraWxh
  rootUser: cm9vdA==
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mlflow-mysql-store
spec:
  secretName: mysql-creds
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 1
