apiVersion: v1
kind: Secret
metadata:
  name: spira-minio-tenant-secret
type: Opaque
data:
  minio_access_key: WHgzeUtaNklvWWdRQmFyMw==
  minio_secret_key: Nk9Od0NXTkZoYk53c3Jld0lGMWpOaE1yY3JuWEllUlk=