exporter:
  # You have to enable exporter first
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: spira
    labels:
      release: kube-prom

config:
  cluster:
    enabled: true
    replicas: 3