apiVersion: v1
kind: Pod
metadata:
  name: spira-api-test-pod
spec:
  containers:
    - name: spira-api-test
      image: busybox
      command: ["sleep", "infinity"]
      tty: true
      env:
        - name: M_CONN_URL
          valueFrom:
            secretKeyRef:
              name: example-mongodb-admin-my-user
              key: connectionString.standardSrv
        - name: nats_conn_url
          value: nats://my-nats:4222
      envFrom:
        - configMapRef:
            name: mongo-client-env
        - configMapRef:
            name: minio-configmap
        - configMapRef:
            name: message-listener-configmap
        - configMapRef:
            name: jwt-auth-configmap
        - secretRef:
            name: spira-minio-tenant-secret
      # Add any additional configuration or resource limits here