kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: spira
  name: kill-pg
spec:
  schedule: '*/1 * * * *'
  startingDeadlineSeconds: null
  concurrencyPolicy: Forbid
  historyLimit: 1000
  type: PodChaos
  podChaos:
    selector:
      namespaces:
        - spira
      labelSelectors:
        cluster-name: spira-pg-cluster
    mode: one
    action: pod-kill
