
apiVersion: v1
kind: Service
metadata:
  name: spira-api-server
spec:
  selector:
    app: spira-api-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spira-api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spira-api-server
  template:
    metadata:
      labels:
        app: spira-api-server
    spec:
      containers:
      - name: spira-api-test
        image: uspcodelab/spira-api:latest
        env:
          - name: M_CONN_URL
            valueFrom:
              secretKeyRef:
                name: example-mongodb-admin-my-user
                key: connectionString.standard
        command: ["python3", "main.py"]
        ports:
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: mongo-client-env
          - configMapRef:
              name: minio-configmap
          - configMapRef:
              name: message-listener-configmap
          - configMapRef:
              name: jwt-auth-configmap
          - secretRef:
              name: spira-minio-tenant-secret